version: 2.0
jobs:
  build:
    machine: true
        
    steps:
      - checkout
      - run:
          name: Clone qxf2/cars-api repo
          command: |
            git clone https://github.com/qxf2/cars-api.git 
      - run:
          name: Install flask as it is needed to run our cars-api web server
          command: | 
            pip install Flask
      - run:
          name: Run cars-app server in background as it is mandatory to run our API test
          command: | 
            python cars-api/cars_app.py
          background: true
      - run:
          name: Wait for sometime to start the server
          command: |
            sleep 5
      - run:
          name: Install requests
          command: |
            pip install -r requirements.txt
      - run:
          dependencies:
            pre:
              # update locally with:
              # openssl aes-256-cbc -e -in .conf/remote_credentials.py -.conf/remote_credentials_circle.py -k $KEY
              openssl aes-256-cbc -d -in .conf/remote_credentials_circle.py -k $KEY >> ~/.circlerc
        
      - run:
          name: Run the API and Selenium tests only (Ignoring to run mobile test as we are not yet set to run mobile test on server)
          command: |
            py.test -s -v --ignore=./tests/test_mobile_bitcoin_price.py --ignore=./tests/test_api_example.py -M Y --junitxml=test-reports/junit.xml --tb=native 
      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file