version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: Clone qxf2/cars-api repo
          command: |
            git clone https://github.com/qxf2/cars-api.git 
      - run:
          name: Install flask as it is needed to run our cars-api web server
          command: | 
            sudo pip install Flask
          name: Install requests
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Decrypt remote_credentials_enc.py using openssl
          command: |
            openssl aes-256-cbc -d -in ./conf/remote_credentials_enc.py -out ./conf/remote_credentials.py -pass env:KEY     
      - run:
          name: Run the API and Selenium tests only (Ignoring to run mobile test as we are not yet set to run mobile test on server)
          command: |
            py.test -s -v --ignore=./tests/test_mobile_bitcoin_price.py -M Y --remote_project_name Qxf2_Selenium_POM --remote_build_name Selenium_Tutorial --junitxml=test-reports/junit.xml --tb=native 
      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file